<?xml version="1.0" encoding="utf-8"?><Database Name="avendaño" Class="dbUsuarioDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=172.16.139.254;Initial Catalog=avendaño;Persist Security Info=True;User ID=tecnicatura" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="avendañoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Usuarios" Member="Usuarios">
    <Type Name="Usuario">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NombreUsuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ClaveAcceso" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="RolUsuario" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>